### ISSUE TITLE
Create a customize bootstrap template

### ISSUE THREAD

**Issue by ooade** [SchoolReviews/SchoolReviews#1]
Follow this guide https://medium.com/@tacomanator/customizing-create-react-app-aa9ffb88165 after getting the Palette

**Comment by hacktivist123** [comment]
okay...Thanks

**Comment by ooade** [comment]
You can also pick a nice purple here https://material.io/guidelines/style/color.html#color-color-palette

**Comment by ooade** [comment]
Check this out - https://material-ui-next.com/
It's a really really nice UI library that will probably meet future needs

**Comment by hacktivist123** [comment]
okay
